### ISSUE TITLE
Image thumbnails of deleted files don't get removed/overwritten

### ISSUE THREAD

**Issue by anonwaha** [Heyuri/Uploader#25]
When in image list mode, it's possible for a file to erroneous display the thumbnail of a previously deleted file. Likely due to the old thumbnail not being deleted along with the actual file, nor overwritten when a new file with the same filename is made.

**Comment by kaguy4** [comment]
★ COW > but thumbnails for videos are in jpg https://github.com/Heyuri/Uploader/blob/61ad7ba81110d75325ec5448a8da918b7e17485c/warota.php#L818 (2024/12/30-06:12:37)
★ COW > when deleting thumbnails, the code assumes the thumbnail has the same extension as the original file. https://github.com/Heyuri/Uploader/blob/61ad7ba81110d75325ec5448a8da918b7e17485c/warota.php#L838 (2024/12/30-06:10:38)

**Comment by kaguy4** [comment]
fixed by https://github.com/Heyuri/Uploader/commit/2231395fb06c9d5e06a8b0a2fc7c138a1249e63c & https://github.com/Heyuri/Uploader/commit/736f2eec8ee3589f59d0976e2165233d07be7780
